### ISSUE TITLE
Someone with codex access please test

### ISSUE THREAD

**Issue by WilliamWelsh** [WilliamWelsh/OpenAI.Net#1]
Hi. If anyone with OpenAI Codex access sees this page, it would be really great if you could test out this library with it. I don't have access so I am unable to test. There is a [SQL Translate example project](https://github.com/WilliamWelsh/OpenAI.Net/blob/main/samples/SQLTranslate/Program.cs) in the samples folder that uses the `davinci-codex`. `cushman-codex` is available as well.

**Comment by WilliamWelsh** [comment]
Forgot to close, I got codex

**Comment by benedlore** [comment]
Does it work with codex?

**Comment by WilliamWelsh** [comment]
> Does it work with codex?

Yes. https://github.com/WilliamWelsh/OpenAI.Net/blob/5c8d1a5abe4fffe3acc563915c50b4e374fed9ab/samples/SQLTranslate/Program.cs

**Comment by benedlore** [comment]
Ah, thanks William
