### ISSUE TITLE
Paraphrase ?...

### ISSUE THREAD

**Issue by effi10** [WilliamWelsh/OpenAI.Net#2]
Hi William

Is it possible to paraphrase some texts with your wrapper ?

I understood all functions you've implemented (it's great !) and it's possible I use it in next weeks for my personal use. 

Great job !

**Comment by WilliamWelsh** [comment]
Hey. You sure can. There's a few examples on the OpenAI site and one of them is in the examples folder. On the OpenAI playground I made this setup:

![image](https://user-images.githubusercontent.com/16886888/153446208-28c92252-87fb-4ac7-8a45-b9fe53c1b13c.png)

And it produced:

> Elon Reeve Musk is a business magnate and entrepreneur who founded SpaceX, Tesla, Inc., The Boring Company, Neuralink, and OpenAI. He is also the co-founder of SolarCity and X.com. With an estimated net worth of around US$243 billion as of February 2022

So you can just replicate that setup with the wrapper.

Summarize for a 2nd grader example: https://beta.openai.com/examples/default-summarize
Notes to summary example: https://beta.openai.com/examples/default-notes-summary

The notes to summary example is available in the examples folder here: https://github.com/WilliamWelsh/OpenAI.Net/blob/main/samples/NotesToSummary/Program.cs

**Comment by WilliamWelsh** [comment]
I'm gonna go ahead and close this after a month of no response, but like I said it's easily possible with the wrapper. Feel free to re-open if you need help.
