### ISSUE TITLE
Can you add a new user parameter for this nuget?

### ISSUE THREAD

**Issue by BigHeadDev** [WilliamWelsh/OpenAI.Net#6]
Hello Sir:
    Your nuget and asp. net core really match！I feel great using it.
    But recently we found a new demand，When **many users** call my API service at the same time, the context of OpenAI is always one person, which results in poor user experience
    I found a parameter End user IDs on the OpenAI API doc，This parameter seems to solve my problem
    So, can you please add an extension method of .WithUser("user123")? thank you very much indeed
![lQLPJxrr_7QzLSjNAf3NA9-wjfc8gEiPYhADn-nwdUBJAQ_991_509](https://user-images.githubusercontent.com/23449064/209106271-d657b238-4824-4bf5-989c-ac2d87395fe9.png)

**Comment by WilliamWelsh** [comment]
Sure can.

**Comment by WilliamWelsh** [comment]
Package update is available, can you confirm that it works for your need?
